In [12]:
import numpy as np
arr1=np.array([[10,25,33,42,55],[12,33,46,42,89],[38,46,62,99,53],[18,35,42,64,77]])
arr1
total_sum=np.sum(arr1)
row_sum=np.sum(arr1,axis=1)
print("Total Sum of array= ",total_sum)
print("Row sum of array= ",row_sum)
col_sum=np.sum(arr1,axis=0)
print("Column sum of array= ",col_sum)

Total Sum of array=  921
Row sum of array=  [165 222 298 236]
Column sum of array=  [ 78 139 183 247 274]


In [19]:
arr1=np.array([[10,25,33,42,55],[12,33,46,42,89],[38,46,62,99,53],[18,35,42,64,77]])
spec_no=50
less_than= arr1[arr1<spec_no]
greater_than=arr1[arr1>spec_no]
print(f"The array is:\n{arr1}")
print(f"The numbers less than {spec_no} is:\n{less_than}")
print(f"The numbers greater than {spec_no} is:\n{greater_than}")

The array is:
[[10 25 33 42 55]
 [12 33 46 42 89]
 [38 46 62 99 53]
 [18 35 42 64 77]]
The numbers less than 50 is:
[10 25 33 42 12 33 46 42 38 46 18 35 42]
The numbers greater than 50 is:
[55 89 62 99 53 64 77]


In [34]:
import numpy.random
ar1 = np.random.randint(0, 50, size=(4, 4))
ar2 = np.random.randint(50,100, size=(4,4))
ar3 = np.random.randint(100,200, size=(4,4))

concat1= np.concatenate((ar1,ar2,ar3),axis=1)
concat2= np.concatenate((ar1,ar2,ar3),axis=0)

print(f"The arrays are:\narray1:\n{ar1}\narray2:\n{ar2}\narray3:\n{ar3}")
print(f"The arrays concatenated as rows is:\n{concat1}")
print(f"The arrays concatenated as columns is:\n{concat2}")


The arrays are:
array1:
[[39 49 12  0]
 [28 45 29 19]
 [13  5 43 12]
 [ 6 13 42 14]]
array2:
[[93 84 68 93]
 [60 54 94 55]
 [99 75 78 69]
 [66 61 89 99]]
array3:
[[199 149 180 138]
 [120 184 164 144]
 [179 134 195 157]
 [153 174 105 169]]
The arrays concatenated as rows is:
[[ 39  49  12   0  93  84  68  93 199 149 180 138]
 [ 28  45  29  19  60  54  94  55 120 184 164 144]
 [ 13   5  43  12  99  75  78  69 179 134 195 157]
 [  6  13  42  14  66  61  89  99 153 174 105 169]]
The arrays concatenated as columns is:
[[ 39  49  12   0]
 [ 28  45  29  19]
 [ 13   5  43  12]
 [  6  13  42  14]
 [ 93  84  68  93]
 [ 60  54  94  55]
 [ 99  75  78  69]
 [ 66  61  89  99]
 [199 149 180 138]
 [120 184 164 144]
 [179 134 195 157]
 [153 174 105 169]]
